apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.model.auth }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.model.auth }}
  AWS_ENDPOINT_URL: {{ .Values.model.endpoint }}
  USE_SSL: {{ quote .Values.model.ssl }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsi-deployment-sa
secrets:
  - name: minio-credentials
